<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RepositoryUrl>https://github.com/lstratman/insight-docs</RepositoryUrl>
    <PackageDescription>Template for InsightDocs that mimics the appearance of the Microsoft Learning site</PackageDescription>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets/**/*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InsightDocs\InsightDocs.csproj" />
  </ItemGroup>

</Project>
