<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RepositoryUrl>https://github.com/lstratman/insight-docs</RepositoryUrl>
    <PackageDescription>Provides the ability for InsightDocs to publish to and serve topics from a SQLite database</PackageDescription>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InsightDocs\InsightDocs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.3.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.17" />
    <PackageReference Include="MimeTypes" Version="2.5.2" />
    <PackageReference Include="NUglify" Version="1.21.15" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\**\*" />
  </ItemGroup>

</Project>
