<Project>
  <PropertyGroup>
    <RepositoryUrl>https://github.com/lstratman/insight-docs</RepositoryUrl>
    <BaseVersion>0.9</BaseVersion>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(BuildNumber)' == ''">
    <Version>$(BaseVersion).0</Version>
    <PackageVersion>$(BaseVersion).0</PackageVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(BuildNumber)' != ''">
    <Version>$(BaseVersion).$(BuildNumber)</Version>
    <PackageVersion>$(BaseVersion).$(BuildNumber)</PackageVersion>
  </PropertyGroup>
</Project>