<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>InsightDocs</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RepositoryUrl>https://github.com/lstratman/insight-docs</RepositoryUrl>
    <PackageDescription>Core library for InsightDocs</PackageDescription>
    <Version>0.9.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="8.0.0" />
    <PackageReference Include="System.Reflection.MetadataLoadContext" Version="8.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.15" />
    <PackageReference Include="Markdig" Version="0.41.2" />
    <PackageReference Include="MimeTypes" Version="2.5.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
