using InsightDocs.Abstractions;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace InsightDocs.TypeScript.Model;

public class TypeScriptTypeDeclarationConverter : JsonConverter
{
    public override bool CanConvert(Type objectType)
    {
        return objectType == typeof(TypeScriptTypeDeclaration);
    }

    public override object ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer)
    {
        return ReadJson(JObject.Load(reader), serializer);
    }

    public static object ReadJson(JObject jsonObject, JsonSerializer serializer)
    {
        if (!jsonObject.ContainsKey("kind"))
        {
            throw new Exception("TypeScript type declaration JSON object does not contain 'kind' property.");
        }

        TypeScriptTypeDeclaration typeDeclarationObject = jsonObject["kind"]!.Value<string>() switch
        {
            "interface" => new TypeScriptInterface(),
            "alias" => new TypeScriptTypeAlias(),
            "enum" => new TypeScriptEnum(),
            "variable" => new TypeScriptVariable(),
            _ => throw new Exception("Unrecognized TypeScript type declaration type: " + jsonObject["kind"]!.Value<string>() + "."),
        };

        serializer.Populate(jsonObject.CreateReader(), typeDeclarationObject);
        return typeDeclarationObject;
    }

    public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
    {
        throw new NotImplementedException();
    }
}

public abstract class TypeScriptNamespacedTypeDeclaration : TypeScriptTypeDeclaration
{
    public TypeScriptNamespace? Namespace
    {
        get;
        set;
    }
}

[JsonConverter(typeof(TypeScriptTypeDeclarationConverter))]
public abstract class TypeScriptTypeDeclaration : ILinkTarget
{
    public static readonly Dictionary<string, string> MDNUrlMappings = new Dictionary<string, string>
    {
        { "https://developer.mozilla.org/docs/Web/API/HTMLElement/cancel_event", "https://developer.mozilla.org/docs/Web/API/HTMLElement" },
        { "https://developer.mozilla.org/docs/Web/API/HTMLDialogElement/cancel_event", "https://developer.mozilla.org/docs/Web/API/HTMLElement" },
        { "https://developer.mozilla.org/docs/Web/API/HTMLVideoElement/resize_event", "https://developer.mozilla.org/docs/Web/API/VisualViewport/resize_event" },
        { "https://developer.mozilla.org/docs/Web/API/HTMLTableRowElement/cells", "https://developer.mozilla.org/docs/Web/API/HTMLTableRowElement" },
        { "https://developer.mozilla.org/docs/Web/API/HTMLTableRowElement/sectionRowIndex", "https://developer.mozilla.org/docs/Web/API/HTMLTableRowElement" },
        { "https://developer.mozilla.org/docs/Web/API/HTMLTableCellElement/colSpan", "https://developer.mozilla.org/docs/Web/API/HTMLTableCellElement" },
        { "https://developer.mozilla.org/docs/Web/API/HTMLTableCellElement/cellIndex", "https://developer.mozilla.org/docs/Web/API/HTMLTableCellElement" },
        { "https://developer.mozilla.org/docs/Web/API/HTMLTableCellElement/abbr", "https://developer.mozilla.org/docs/Web/API/HTMLTableCellElement" },
        { "https://developer.mozilla.org/docs/Web/API/HTMLTableCellElement/rowSpan", "https://developer.mozilla.org/docs/Web/API/HTMLTableCellElement" },
        { "https://developer.mozilla.org/docs/Web/API/HTMLTableCellElement/headers", "https://developer.mozilla.org/docs/Web/API/HTMLTableCellElement" },
        { "https://developer.mozilla.org/docs/Web/API/HTMLTableCellElement/scope", "https://developer.mozilla.org/docs/Web/API/HTMLTableCellElement" }
    };

    public static readonly Dictionary<string, string> TypeScriptTypes = new Dictionary<string, string>
    {
        { "Awaited", "awaitedtype" },
        { "NonNullable", "nonnullabletype" },
        { "Parameters", "parameterstype" },
        { "ConstructorParameters", "constructorparameterstype" },
        { "ReturnType", "returntypetype" },
        { "InstanceType", "instancetypetype" },
        { "ThisParameterType", "thisparametertype" },
        { "OmitThisParameter", "omitthisparametertype" },
        { "Required", "requiredtype" },
        { "Uppercase", "uppercasestringtype" },
        { "Lowercase", "lowercasestringtype" },
        { "Capitalize", "capitalizestringtype" },
        { "Uncapitalize", "uncapitalizestringtype" },
        { "Record", "recordkeys-type" },
        { "Partial", "partialtype" },
        { "Pick", "picktype-keys" },
        { "Exclude", "excludeuniontype-excludedmembers" },
        { "Readonly", "readonlytype" },
        { "Omit", "omittype-keys" },
        { "Extract", "extracttype-union" },
        { "ThisType<T>", "thistypetype" }
    };

    public static readonly Dictionary<string, string> JavaScriptTypeMappings = new Dictionary<string, string>
    {
        { "ElementCSSInlineStyle", "HTMLElement" },
        { "HTMLOrSVGElement", "SVGElement" },
        { "NonDocumentTypeChildNode", "Node" },
        { "DocumentAndElementEventHandlers", "HTMLElement" },
        { "DocumentAndElementEventHandlersEventMap", "Event" },
        { "GlobalEventHandlersEventMap", "Event" },
        { "InnerHTML", "Element" },
        { "ElementContentEditable", "HTMLElement" },
        { "Animatable", "Element" },
        { "DocumentEvent", "Event" },
        { "NodeListOf", "NodeList" },
        { "ObjectConstructor", "Object" },
        { "ActiveXObject", "Object" },
        { "ChildNode", "Node" },
        { "RegExpExecArray", "Array" },
        { "RegExpMatchArray", "Array" },
        { "ARIAMixin", "Element" },
        { "Slottable", "Element" },
        { "ParentNode", "Node" },
        { "PromiseLike", "Promise" },
        { "Iterable", "Iterator" },
        { "iterator", "Iterator" },
        { "ArrayLike", "Array" },
        { "PropertyKey", "String" },
        { "ElementEventMap", "Event" },
        { "HTMLElementEventMap", "Event" },
        { "HTMLCollectionOf", "NodeList" },
        { "CanvasRenderingContext2DSettings", "CanvasRenderingContext2D" },
        { "HTMLTableHeaderCellElement", "HTMLTableCellElement" },
        { "HTMLFrameElement", "HTMLElement" },
        { "DocumentOrShadowRoot", "Document" },
        { "FontFaceSource", "FontFace" },
        { "XPathEvaluatorBase", "XPathEvaluator" },
        { "IterableIterator", "Iterator" },
        { "EventListenerOrEventListenerObject", "EventTarget" },
        { "EventListener", "EventTarget" },
        { "AddEventListenerOptions", "EventTarget" },
        { "CustomElementConstructor", "HTMLElement" },
        { "CanvasLineJoin", "CanvasRenderingContext2D" },
        { "CanvasLineCap", "CanvasRenderingContext2D" },
        { "CanvasTextAlign", "CanvasRenderingContext2D" },
        { "CanvasTextBaseline", "CanvasRenderingContext2D" },
        { "NumberFormatOptions", "Intl.NumberFormat" },
        { "NonElementParentNode", "Node" }
    };

    public static readonly string[] JavaScriptGlobalObjects =
    [
        "Object",
        "Function",
        "Boolean",
        "Symbol",
        "Error",
        "AggregateError",
        "EvalError",
        "RangeError",
        "ReferenceError",
        "SyntaxError",
        "TypeError",
        "URIError",
        "InternalError",
        "Number",
        "BigInt",
        "Math",
        "Date",
        "String",
        "RegExp",
        "Array",
        "Int8Array",
        "Uint8Array",
        "Uint8ClampedArray",
        "Int16Array",
        "Uint16Array",
        "Int32Array",
        "Uint32Array",
        "BigInt64Array",
        "BigUint64Array",
        "Float32Array",
        "Float64Array",
        "Map",
        "Set",
        "WeakMap",
        "WeakSet",
        "ArrayBuffer",
        "SharedArrayBuffer",
        "DataView",
        "Atomics",
        "JSON",
        "WeakRef",
        "FinalizationRegistry",
        "Iterator",
        "AsyncIterator",
        "Promise",
        "GeneratorFunction",
        "AsyncGeneratorFunction",
        "Generator",
        "AsyncGenerator",
        "AsyncFunction",
        "Reflection",
        "Reflect",
        "Proxy",
        "Intl",
        "Intl.NumberFormat"
    ];

    public static readonly string[] JavaScriptBuiltinTypes =
    [
        "AbortController",
        "AbortSignal",
        "AbsoluteOrientationSensor",
        "AbstractRange",
        "Accelerometer",
        "AesCbcParams",
        "AesCtrParams",
        "AesGcmParams",
        "AesKeyGenParams",
        "AmbientLightSensor",
        "AnalyserNode",
        "Animation",
        "AnimationEffect",
        "AnimationEvent",
        "AnimationPlaybackEvent",
        "AnimationTimeline",
        "Attr",
        "AudioBuffer",
        "AudioBufferSourceNode",
        "AudioContext",
        "AudioData",
        "AudioDecoder",
        "AudioDestinationNode",
        "AudioEncoder",
        "AudioListener",
        "AudioNode",
        "AudioParam",
        "AudioParamDescriptor",
        "AudioParamMap",
        "AudioProcessingEvent",
        "AudioScheduledSourceNode",
        "AudioSinkInfo",
        "AudioTrack",
        "AudioTrackList",
        "AudioWorklet",
        "AudioWorkletGlobalScope",
        "AudioWorkletNode",
        "AudioWorkletProcessor",
        "AuthenticatorAssertionResponse",
        "AuthenticatorAttestationResponse",
        "AuthenticatorResponse",
        "BackgroundFetchEvent",
        "BackgroundFetchManager",
        "BackgroundFetchRecord",
        "BackgroundFetchRegistration",
        "BackgroundFetchUpdateUIEvent",
        "BarcodeDetector",
        "BarProp",
        "BaseAudioContext",
        "BatteryManager",
        "BeforeInstallPromptEvent",
        "BeforeUnloadEvent",
        "BiquadFilterNode",
        "Blob",
        "BlobEvent",
        "Bluetooth",
        "BluetoothCharacteristicProperties",
        "BluetoothDevice",
        "BluetoothRemoteGATTCharacteristic",
        "BluetoothRemoteGATTDescriptor",
        "BluetoothRemoteGATTServer",
        "BluetoothRemoteGATTService",
        "BluetoothUUID",
        "BroadcastChannel",
        "ByteLengthQueuingStrategy",
        "Cache",
        "CacheStorage",
        "CanMakePaymentEvent",
        "CanvasCaptureMediaStreamTrack",
        "CanvasGradient",
        "CanvasPattern",
        "CanvasRenderingContext2D",
        "CaptureController",
        "CaretPosition",
        "CDATASection",
        "ChannelMergerNode",
        "ChannelSplitterNode",
        "CharacterBoundsUpdateEvent",
        "CharacterData",
        "Client",
        "Clients",
        "Clipboard",
        "ClipboardEvent",
        "ClipboardItem",
        "CloseEvent",
        "Comment",
        "CompositionEvent",
        "CompressionStream",
        "console",
        "ConstantSourceNode",
        "ContactAddress",
        "ContactsManager",
        "ContentIndex",
        "ContentIndexEvent",
        "ContentVisibilityAutoStateChangeEvent",
        "ConvolverNode",
        "CookieChangeEvent",
        "CookieStore",
        "CookieStoreManager",
        "CountQueuingStrategy",
        "Credential",
        "CredentialsContainer",
        "Crypto",
        "CryptoKey",
        "CryptoKeyPair",
        "CSPViolationReportBody",
        "CSS",
        "CSSAnimation",
        "CSSConditionRule",
        "CSSContainerRule",
        "CSSCounterStyleRule",
        "CSSFontFaceRule",
        "CSSFontFeatureValuesRule",
        "CSSFontPaletteValuesRule",
        "CSSGroupingRule",
        "CSSImageValue",
        "CSSImportRule",
        "CSSKeyframeRule",
        "CSSKeyframesRule",
        "CSSKeywordValue",
        "CSSLayerBlockRule",
        "CSSLayerStatementRule",
        "CSSMathInvert",
        "CSSMathMax",
        "CSSMathMin",
        "CSSMathNegate",
        "CSSMathProduct",
        "CSSMathSum",
        "CSSMathValue",
        "CSSMatrixComponent",
        "CSSMediaRule",
        "CSSNamespaceRule",
        "CSSNumericArray",
        "CSSNumericValue",
        "CSSPageRule",
        "CSSPerspective",
        "CSSPositionValue",
        "CSSPrimitiveValue",
        "CSSPropertyRule",
        "CSSPseudoElement",
        "CSSRotate",
        "CSSRule",
        "CSSRuleList",
        "CSSScale",
        "CSSScopeRule",
        "CSSSkew",
        "CSSSkewX",
        "CSSSkewY",
        "CSSStartingStyleRule",
        "CSSStyleDeclaration",
        "CSSStyleRule",
        "CSSStyleSheet",
        "CSSStyleValue",
        "CSSSupportsRule",
        "CSSTransformComponent",
        "CSSTransformValue",
        "CSSTransition",
        "CSSTranslate",
        "CSSUnitValue",
        "CSSUnparsedValue",
        "CSSValue",
        "CSSValueList",
        "CSSVariableReferenceValue",
        "CustomElementRegistry",
        "CustomEvent",
        "CustomStateSet",
        "DataTransfer",
        "DataTransferItem",
        "DataTransferItemList",
        "DecompressionStream",
        "DedicatedWorkerGlobalScope",
        "DelayNode",
        "DeprecationReportBody",
        "DeviceMotionEvent",
        "DeviceMotionEventAcceleration",
        "DeviceMotionEventRotationRate",
        "DeviceOrientationEvent",
        "DirectoryEntrySync",
        "DirectoryReaderSync",
        "Document",
        "DocumentFragment",
        "DocumentPictureInPicture",
        "DocumentPictureInPictureEvent",
        "DocumentTimeline",
        "DocumentType",
        "DOMError",
        "DOMException",
        "DOMHighResTimeStamp",
        "DOMImplementation",
        "DOMMatrixReadOnly",
        "DOMParser",
        "DOMPoint",
        "DOMPointReadOnly",
        "DOMQuad",
        "DOMRect",
        "DOMRectReadOnly",
        "DOMStringList",
        "DOMStringMap",
        "DOMTokenList",
        "DragEvent",
        "DynamicsCompressorNode",
        "EcdhKeyDeriveParams",
        "EcdsaParams",
        "EcKeyGenParams",
        "EcKeyImportParams",
        "EditContext",
        "Element",
        "ElementInternals",
        "EncodedAudioChunk",
        "EncodedVideoChunk",
        "ErrorEvent",
        "Event",
        "EventCounts",
        "EventSource",
        "EventTarget",
        "ExtendableCookieChangeEvent",
        "ExtendableEvent",
        "ExtendableMessageEvent",
        "EyeDropper",
        "FeaturePolicy",
        "FederatedCredential",
        "Fence",
        "FencedFrameConfig",
        "FetchEvent",
        "File",
        "FileEntrySync",
        "FileList",
        "FileReader",
        "FileReaderSync",
        "FileSystem",
        "FileSystemDirectoryEntry",
        "FileSystemDirectoryHandle",
        "FileSystemDirectoryReader",
        "FileSystemEntry",
        "FileSystemFileEntry",
        "FileSystemFileHandle",
        "FileSystemHandle",
        "FileSystemSync",
        "FileSystemSyncAccessHandle",
        "FileSystemWritableFileStream",
        "FocusEvent",
        "FontData",
        "FontFace",
        "FontFaceSet",
        "FontFaceSetLoadEvent",
        "FormData",
        "FormDataEvent",
        "FragmentDirective",
        "GainNode",
        "Gamepad",
        "GamepadButton",
        "GamepadEvent",
        "GamepadHapticActuator",
        "GamepadPose",
        "Geolocation",
        "GeolocationCoordinates",
        "GeolocationPosition",
        "GeolocationPositionError",
        "GestureEvent",
        "GPU",
        "GPUAdapter",
        "GPUAdapterInfo",
        "GPUBindGroup",
        "GPUBindGroupLayout",
        "GPUBuffer",
        "GPUCanvasContext",
        "GPUCommandBuffer",
        "GPUCommandEncoder",
        "GPUCompilationInfo",
        "GPUCompilationMessage",
        "GPUComputePassEncoder",
        "GPUComputePipeline",
        "GPUDevice",
        "GPUDeviceLostInfo",
        "GPUError",
        "GPUExternalTexture",
        "GPUInternalError",
        "GPUOutOfMemoryError",
        "GPUPipelineError",
        "GPUPipelineLayout",
        "GPUQuerySet",
        "GPUQueue",
        "GPURenderBundle",
        "GPURenderBundleEncoder",
        "GPURenderPassEncoder",
        "GPURenderPipeline",
        "GPUSampler",
        "GPUShaderModule",
        "GPUSupportedFeatures",
        "GPUSupportedLimits",
        "GPUTexture",
        "GPUTextureView",
        "GPUUncapturedErrorEvent",
        "GPUValidationError",
        "GravitySensor",
        "Gyroscope",
        "HashChangeEvent",
        "Headers",
        "HID",
        "HIDConnectionEvent",
        "HIDDevice",
        "HIDInputReportEvent",
        "Highlight",
        "HighlightRegistry",
        "History",
        "HkdfParams",
        "HmacImportParams",
        "HmacKeyGenParams",
        "HMDVRDevice",
        "HTMLAllCollection",
        "HTMLAnchorElement",
        "HTMLAreaElement",
        "HTMLAudioElement",
        "HTMLBaseElement",
        "HTMLBodyElement",
        "HTMLBRElement",
        "HTMLButtonElement",
        "HTMLCanvasElement",
        "HTMLCollection",
        "HTMLDataElement",
        "HTMLDataListElement",
        "HTMLDetailsElement",
        "HTMLDialogElement",
        "HTMLDivElement",
        "HTMLDListElement",
        "HTMLDocument",
        "HTMLElement",
        "HTMLEmbedElement",
        "HTMLFencedFrameElement",
        "HTMLFieldSetElement",
        "HTMLFontElement",
        "HTMLFormControlsCollection",
        "HTMLFormElement",
        "HTMLFrameSetElement",
        "HTMLHeadElement",
        "HTMLHeadingElement",
        "HTMLHRElement",
        "HTMLHtmlElement",
        "HTMLIFrameElement",
        "HTMLImageElement",
        "HTMLInputElement",
        "HTMLLabelElement",
        "HTMLLegendElement",
        "HTMLLIElement",
        "HTMLLinkElement",
        "HTMLMapElement",
        "HTMLMarqueeElement",
        "HTMLMediaElement",
        "HTMLMenuElement",
        "HTMLMenuItemElement",
        "HTMLMetaElement",
        "HTMLMeterElement",
        "HTMLModElement",
        "HTMLObjectElement",
        "HTMLOListElement",
        "HTMLOptGroupElement",
        "HTMLOptionElement",
        "HTMLOptionsCollection",
        "HTMLOutputElement",
        "HTMLParagraphElement",
        "HTMLParamElement",
        "HTMLPictureElement",
        "HTMLPreElement",
        "HTMLProgressElement",
        "HTMLQuoteElement",
        "HTMLScriptElement",
        "HTMLSelectElement",
        "HTMLSlotElement",
        "HTMLSourceElement",
        "HTMLSpanElement",
        "HTMLStyleElement",
        "HTMLTableCaptionElement",
        "HTMLTableCellElement",
        "HTMLTableColElement",
        "HTMLTableElement",
        "HTMLTableRowElement",
        "HTMLTableSectionElement",
        "HTMLTemplateElement",
        "HTMLTextAreaElement",
        "HTMLTimeElement",
        "HTMLTitleElement",
        "HTMLTrackElement",
        "HTMLUListElement",
        "HTMLUnknownElement",
        "HTMLVideoElement",
        "IDBCursor",
        "IDBCursorWithValue",
        "IDBDatabase",
        "IDBFactory",
        "IDBIndex",
        "IDBKeyRange",
        "IDBObjectStore",
        "IDBOpenDBRequest",
        "IDBRequest",
        "IDBTransaction",
        "IDBVersionChangeEvent",
        "IdentityCredential",
        "IdentityProvider",
        "IdleDeadline",
        "IdleDetector",
        "IIRFilterNode",
        "ImageBitmap",
        "ImageBitmapRenderingContext",
        "ImageCapture",
        "ImageData",
        "ImageDecoder",
        "ImageTrack",
        "ImageTrackList",
        "Ink",
        "InkPresenter",
        "InputDeviceCapabilities",
        "InputDeviceInfo",
        "InputEvent",
        "InstallEvent",
        "IntersectionObserver",
        "IntersectionObserverEntry",
        "InterventionReportBody",
        "Keyboard",
        "KeyboardEvent",
        "KeyboardLayoutMap",
        "KeyframeEffect",
        "LargestContentfulPaint",
        "LaunchParams",
        "LaunchQueue",
        "LayoutShift",
        "LayoutShiftAttribution",
        "LinearAccelerationSensor",
        "Location",
        "Lock",
        "LockManager",
        "Magnetometer",
        "MathMLElement",
        "MediaCapabilities",
        "MediaDeviceInfo",
        "MediaDevices",
        "MediaElementAudioSourceNode",
        "MediaEncryptedEvent",
        "MediaError",
        "MediaKeyMessageEvent",
        "MediaKeys",
        "MediaKeySession",
        "MediaKeyStatusMap",
        "MediaKeySystemAccess",
        "MediaList",
        "MediaMetadata",
        "MediaQueryList",
        "MediaQueryListEvent",
        "MediaRecorder",
        "MediaRecorderErrorEvent",
        "MediaSession",
        "MediaSource",
        "MediaSourceHandle",
        "MediaStream",
        "MediaStreamAudioDestinationNode",
        "MediaStreamAudioSourceNode",
        "MediaStreamEvent",
        "MediaStreamTrack",
        "MediaStreamTrackAudioSourceNode",
        "MediaStreamTrackEvent",
        "MediaStreamTrackGenerator",
        "MediaStreamTrackProcessor",
        "MediaTrackConstraints",
        "MediaTrackSettings",
        "MediaTrackSupportedConstraints",
        "MerchantValidationEvent",
        "MessageChannel",
        "MessageEvent",
        "MessagePort",
        "Metadata",
        "MIDIAccess",
        "MIDIConnectionEvent",
        "MIDIInput",
        "MIDIInputMap",
        "MIDIMessageEvent",
        "MIDIOutput",
        "MIDIOutputMap",
        "MIDIPort",
        "MimeType",
        "MimeTypeArray",
        "MouseEvent",
        "MouseScrollEvent",
        "MutationEvent",
        "MutationObserver",
        "MutationRecord",
        "NamedNodeMap",
        "NavigateEvent",
        "Navigation",
        "NavigationCurrentEntryChangeEvent",
        "NavigationDestination",
        "NavigationHistoryEntry",
        "NavigationPreloadManager",
        "NavigationTransition",
        "Navigator",
        "NavigatorLogin",
        "NavigatorUAData",
        "NDEFMessage",
        "NDEFReader",
        "NDEFReadingEvent",
        "NDEFRecord",
        "NetworkInformation",
        "Node",
        "NodeIterator",
        "NodeList",
        "Notification",
        "NotificationEvent",
        "OfflineAudioCompletionEvent",
        "OfflineAudioContext",
        "OffscreenCanvas",
        "OffscreenCanvasRenderingContext2D",
        "OrientationSensor",
        "OscillatorNode",
        "OTPCredential",
        "OverconstrainedError",
        "PageTransitionEvent",
        "PaintWorkletGlobalScope",
        "PannerNode",
        "PasswordCredential",
        "Path2D",
        "PaymentAddress",
        "PaymentManager",
        "PaymentMethodChangeEvent",
        "PaymentRequest",
        "PaymentRequestEvent",
        "PaymentRequestUpdateEvent",
        "PaymentResponse",
        "Pbkdf2Params",
        "Performance",
        "PerformanceElementTiming",
        "PerformanceEntry",
        "PerformanceEventTiming",
        "PerformanceLongTaskTiming",
        "PerformanceMark",
        "PerformanceMeasure",
        "PerformanceNavigation",
        "PerformanceNavigationTiming",
        "PerformanceObserver",
        "PerformanceObserverEntryList",
        "PerformancePaintTiming",
        "PerformanceResourceTiming",
        "PerformanceServerTiming",
        "PerformanceTiming",
        "PeriodicSyncEvent",
        "PeriodicSyncManager",
        "PeriodicWave",
        "Permissions",
        "PermissionStatus",
        "PictureInPictureEvent",
        "PictureInPictureWindow",
        "Plugin",
        "PluginArray",
        "Point",
        "PointerEvent",
        "PopStateEvent",
        "PositionSensorVRDevice",
        "Presentation",
        "PresentationAvailability",
        "PresentationConnection",
        "PresentationConnectionAvailableEvent",
        "PresentationConnectionCloseEvent",
        "PresentationConnectionList",
        "PresentationReceiver",
        "PresentationRequest",
        "ProcessingInstruction",
        "ProgressEvent",
        "PromiseRejectionEvent",
        "PublicKeyCredential",
        "PushEvent",
        "PushManager",
        "PushMessageData",
        "PushSubscription",
        "PushSubscriptionOptions",
        "RadioNodeList",
        "Range",
        "ReadableByteStreamController",
        "ReadableStream",
        "ReadableStreamBYOBReader",
        "ReadableStreamBYOBRequest",
        "ReadableStreamDefaultController",
        "ReadableStreamDefaultReader",
        "RelativeOrientationSensor",
        "RemotePlayback",
        "Report",
        "ReportBody",
        "ReportingObserver",
        "Request",
        "RequestInit",
        "ResizeObserver",
        "ResizeObserverEntry",
        "ResizeObserverSize",
        "Response",
        "RsaHashedImportParams",
        "RsaHashedKeyGenParams",
        "RsaOaepParams",
        "RsaPssParams",
        "RTCAudioSourceStats",
        "RTCCertificate",
        "RTCCertificateStats",
        "RTCCodecStats",
        "RTCDataChannel",
        "RTCDataChannelEvent",
        "RTCDtlsTransport",
        "RTCDTMFSender",
        "RTCDTMFToneChangeEvent",
        "RTCEncodedAudioFrame",
        "RTCEncodedVideoFrame",
        "RTCError",
        "RTCErrorEvent",
        "RTCIceCandidate",
        "RTCIceCandidatePair",
        "RTCIceCandidatePairStats",
        "RTCIceCandidateStats",
        "RTCIceParameters",
        "RTCIceTransport",
        "RTCIdentityAssertion",
        "RTCInboundRtpStreamStats",
        "RTCOutboundRtpStreamStats",
        "RTCPeerConnection",
        "RTCPeerConnectionIceErrorEvent",
        "RTCPeerConnectionIceEvent",
        "RTCPeerConnectionStats",
        "RTCRemoteOutboundRtpStreamStats",
        "RTCRtpCodecParameters",
        "RTCRtpReceiver",
        "RTCRtpScriptTransform",
        "RTCRtpScriptTransformer",
        "RTCRtpSender",
        "RTCRtpStreamStats",
        "RTCRtpTransceiver",
        "RTCSctpTransport",
        "RTCSessionDescription",
        "RTCStatsReport",
        "RTCTrackEvent",
        "RTCTransformEvent",
        "RTCTransportStats",
        "Sanitizer",
        "Scheduler",
        "Scheduling",
        "Screen",
        "ScreenDetailed",
        "ScreenDetails",
        "ScreenOrientation",
        "ScriptProcessorNode",
        "ScrollTimeline",
        "SecurePaymentConfirmationRequest",
        "SecurityPolicyViolationEvent",
        "Selection",
        "Sensor",
        "SensorErrorEvent",
        "Serial",
        "SerialPort",
        "ServiceWorker",
        "ServiceWorkerContainer",
        "ServiceWorkerGlobalScope",
        "ServiceWorkerRegistration",
        "ShadowRoot",
        "SharedStorage",
        "SharedStorageOperation",
        "SharedStorageRunOperation",
        "SharedStorageSelectURLOperation",
        "SharedStorageWorklet",
        "SharedStorageWorkletGlobalScope",
        "SharedWorker",
        "SharedWorkerGlobalScope",
        "SourceBuffer",
        "SourceBufferList",
        "SpeechGrammar",
        "SpeechGrammarList",
        "SpeechRecognition",
        "SpeechRecognitionAlternative",
        "SpeechRecognitionErrorEvent",
        "SpeechRecognitionEvent",
        "SpeechRecognitionResult",
        "SpeechRecognitionResultList",
        "SpeechSynthesis",
        "SpeechSynthesisErrorEvent",
        "SpeechSynthesisEvent",
        "SpeechSynthesisUtterance",
        "SpeechSynthesisVoice",
        "StaticRange",
        "StereoPannerNode",
        "Storage",
        "StorageEvent",
        "StorageManager",
        "StylePropertyMap",
        "StylePropertyMapReadOnly",
        "StyleSheet",
        "StyleSheetList",
        "SubmitEvent",
        "SubtleCrypto",
        "SVGAElement",
        "SVGAngle",
        "SVGAnimateColorElement",
        "SVGAnimatedAngle",
        "SVGAnimatedBoolean",
        "SVGAnimatedEnumeration",
        "SVGAnimatedInteger",
        "SVGAnimatedLength",
        "SVGAnimatedLengthList",
        "SVGAnimatedNumber",
        "SVGAnimatedNumberList",
        "SVGAnimatedPreserveAspectRatio",
        "SVGAnimatedRect",
        "SVGAnimatedString",
        "SVGAnimatedTransformList",
        "SVGAnimateElement",
        "SVGAnimateMotionElement",
        "SVGAnimateTransformElement",
        "SVGAnimationElement",
        "SVGCircleElement",
        "SVGClipPathElement",
        "SVGComponentTransferFunctionElement",
        "SVGCursorElement",
        "SVGDefsElement",
        "SVGDescElement",
        "SVGElement",
        "SVGEllipseElement",
        "SVGEvent",
        "SVGFEBlendElement",
        "SVGFEColorMatrixElement",
        "SVGFEComponentTransferElement",
        "SVGFECompositeElement",
        "SVGFEConvolveMatrixElement",
        "SVGFEDiffuseLightingElement",
        "SVGFEDisplacementMapElement",
        "SVGFEDistantLightElement",
        "SVGFEDropShadowElement",
        "SVGFEFloodElement",
        "SVGFEFuncAElement",
        "SVGFEFuncBElement",
        "SVGFEFuncGElement",
        "SVGFEFuncRElement",
        "SVGFEGaussianBlurElement",
        "SVGFEImageElement",
        "SVGFEMergeElement",
        "SVGFEMergeNodeElement",
        "SVGFEMorphologyElement",
        "SVGFEOffsetElement",
        "SVGFEPointLightElement",
        "SVGFESpecularLightingElement",
        "SVGFESpotLightElement",
        "SVGFETileElement",
        "SVGFETurbulenceElement",
        "SVGFilterElement",
        "SVGFontElement",
        "SVGFontFaceElement",
        "SVGFontFaceFormatElement",
        "SVGFontFaceNameElement",
        "SVGFontFaceSrcElement",
        "SVGFontFaceUriElement",
        "SVGForeignObjectElement",
        "SVGGElement",
        "SVGGeometryElement",
        "SVGGlyphElement",
        "SVGGlyphRefElement",
        "SVGGradientElement",
        "SVGGraphicsElement",
        "SVGHKernElement",
        "SVGImageElement",
        "SVGLength",
        "SVGLengthList",
        "SVGLinearGradientElement",
        "SVGLineElement",
        "SVGMarkerElement",
        "SVGMaskElement",
        "SVGMetadataElement",
        "SVGMissingGlyphElement",
        "SVGMPathElement",
        "SVGNumber",
        "SVGNumberList",
        "SVGPathElement",
        "SVGPatternElement",
        "SVGPoint",
        "SVGPointList",
        "SVGPolygonElement",
        "SVGPolylineElement",
        "SVGPreserveAspectRatio",
        "SVGRadialGradientElement",
        "SVGRect",
        "SVGRectElement",
        "SVGRenderingIntent",
        "SVGScriptElement",
        "SVGSetElement",
        "SVGStopElement",
        "SVGStringList",
        "SVGStyleElement",
        "SVGSVGElement",
        "SVGSwitchElement",
        "SVGSymbolElement",
        "SVGTextContentElement",
        "SVGTextElement",
        "SVGTextPathElement",
        "SVGTextPositioningElement",
        "SVGTitleElement",
        "SVGTransform",
        "SVGTransformList",
        "SVGTRefElement",
        "SVGTSpanElement",
        "SVGUnitTypes",
        "SVGUseElement",
        "SVGViewElement",
        "SVGVKernElement",
        "SyncEvent",
        "SyncManager",
        "TaskAttributionTiming",
        "TaskController",
        "TaskPriorityChangeEvent",
        "TaskSignal",
        "Text",
        "TextDecoder",
        "TextDecoderStream",
        "TextEncoder",
        "TextEncoderStream",
        "TextFormat",
        "TextFormatUpdateEvent",
        "TextMetrics",
        "TextTrack",
        "TextTrackCue",
        "TextTrackCueList",
        "TextTrackList",
        "TextUpdateEvent",
        "TimeEvent",
        "TimeRanges",
        "ToggleEvent",
        "Touch",
        "TouchEvent",
        "TouchList",
        "TrackEvent",
        "TransformStream",
        "TransformStreamDefaultController",
        "TransitionEvent",
        "TreeWalker",
        "TrustedHTML",
        "TrustedScript",
        "TrustedScriptURL",
        "TrustedTypePolicy",
        "TrustedTypePolicyFactory",
        "UIEvent",
        "URL",
        "URLPattern",
        "URLSearchParams",
        "USB",
        "USBAlternateInterface",
        "USBConfiguration",
        "USBConnectionEvent",
        "USBDevice",
        "USBEndpoint",
        "USBInterface",
        "USBInTransferResult",
        "USBIsochronousInTransferPacket",
        "USBIsochronousInTransferResult",
        "USBIsochronousOutTransferPacket",
        "USBIsochronousOutTransferResult",
        "USBOutTransferResult",
        "UserActivation",
        "ValidityState",
        "VideoColorSpace",
        "VideoDecoder",
        "VideoEncoder",
        "VideoFrame",
        "VideoPlaybackQuality",
        "VideoTrack",
        "VideoTrackList",
        "ViewTimeline",
        "ViewTransition",
        "VirtualKeyboard",
        "VisibilityStateEntry",
        "VisualViewport",
        "VRDisplay",
        "VRDisplayCapabilities",
        "VRDisplayEvent",
        "VREyeParameters",
        "VRFieldOfView",
        "VRFrameData",
        "VRLayerInit",
        "VRPose",
        "VRStageParameters",
        "VTTCue",
        "VTTRegion",
        "WakeLock",
        "WakeLockSentinel",
        "WaveShaperNode",
        "WebGL2RenderingContext",
        "WebGLActiveInfo",
        "WebGLBuffer",
        "WebGLContextEvent",
        "WebGLFramebuffer",
        "WebGLObject",
        "WebGLProgram",
        "WebGLQuery",
        "WebGLRenderbuffer",
        "WebGLRenderingContext",
        "WebGLSampler",
        "WebGLShader",
        "WebGLShaderPrecisionFormat",
        "WebGLSync",
        "WebGLTexture",
        "WebGLTransformFeedback",
        "WebGLUniformLocation",
        "WebGLVertexArrayObject",
        "WebSocket",
        "WebTransport",
        "WebTransportBidirectionalStream",
        "WebTransportDatagramDuplexStream",
        "WebTransportError",
        "WebTransportReceiveStream",
        "WebTransportSendStream",
        "WGSLLanguageFeatures",
        "WheelEvent",
        "Window",
        "WindowClient",
        "WindowControlsOverlay",
        "WindowControlsOverlayGeometryChangeEvent",
        "WindowSharedStorage",
        "Worker",
        "WorkerGlobalScope",
        "WorkerLocation",
        "WorkerNavigator",
        "Worklet",
        "WorkletGlobalScope",
        "WorkletSharedStorage",
        "WritableStream",
        "WritableStreamDefaultController",
        "WritableStreamDefaultWriter",
        "XMLDocument",
        "XMLHttpRequest",
        "XMLHttpRequestEventTarget",
        "XMLHttpRequestUpload",
        "XMLSerializer",
        "XPathEvaluator",
        "XPathException",
        "XPathExpression",
        "XPathNSResolver",
        "XPathResult",
        "XRAnchor",
        "XRAnchorSet",
        "XRBoundedReferenceSpace",
        "XRCompositionLayer",
        "XRCPUDepthInformation",
        "XRCubeLayer",
        "XRCylinderLayer",
        "XRDepthInformation",
        "XREquirectLayer",
        "XRFrame",
        "XRHand",
        "XRHitTestResult",
        "XRHitTestSource",
        "XRInputSource",
        "XRInputSourceArray",
        "XRInputSourceEvent",
        "XRInputSourcesChangeEvent",
        "XRJointPose",
        "XRJointSpace",
        "XRLayer",
        "XRLayerEvent",
        "XRLightEstimate",
        "XRLightProbe",
        "XRMediaBinding",
        "XRPose",
        "XRProjectionLayer",
        "XRQuadLayer",
        "XRRay",
        "XRReferenceSpace",
        "XRReferenceSpaceEvent",
        "XRRenderState",
        "XRRigidTransform",
        "XRSession",
        "XRSessionEvent",
        "XRSpace",
        "XRSubImage",
        "XRSystem",
        "XRTransientInputHitTestResult",
        "XRTransientInputHitTestSource",
        "XRView",
        "XRViewerPose",
        "XRViewport",
        "XRWebGLBinding",
        "XRWebGLDepthInformation",
        "XRWebGLLayer",
        "XRWebGLSubImage",
        "XSLTProcessor"
    ];

    public virtual int Id
    {
        get;
        set;
    }

    [JsonProperty("name")]
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.
    public virtual string Name
#pragma warning restore CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.
    {
        get;
        set;
    }

    [JsonProperty("fullName")]
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.
    public virtual string FullName
#pragma warning restore CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.
    {
        get;
        set;
    }

    [JsonProperty("comment")]
    public Comment? Comment
    {
        get;
        set;
    }

    [JsonProperty("builtIn")]
    public bool BuiltIn
    {
        get;
        set;
    }

    public string? Url
    {
        get;
        set;
    }

    public abstract string Title
    {
        get;
    }

    public virtual string LinkText
    {
        get
        {
            return Name;
        }
    }

    public virtual TypeScriptProject? Project
    {
        get;
        set;
    }

    public virtual void Normalize()
    {
    }
}
